spring:
  cloud:
    stream:
      function:
        definition: function
        bindings:
          function-in-0:
            destination: source
          fucntion-out-0:
            destination: source
        bindingServiceProperties:
          defaultBinder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
  rabbitmq:
    host: localhost
    port: 5672
    username: guset
    password: guest
